// APP_REF_DATA Common Constant

const int ARD_COMMON_KEY_NO_DATA = -1;

const int ARD_COMMON_INVALID_KEY = -99;

const String ARD_COMMON_CITY_NAME = "CITY_NAME";
const String ARD_COMMON_AREA_NAME = "AREA_NAME";


// APP_REF_DATA Property Constant
const String ARD_PROPERTY_TYPE = 'PROPERTY_TYPE';
const String ARD_PROPERTY_TYPE_GROUP = 'PROPERTY_TYPE_GROUP';
const String ARD_PROPERTY_CONFIGURATION_TYPE = 'PROPERTY_CONFIGURATION_TYPE';
const String ARD_PROPERTY_AREA_UNIT = 'PROPERTY_AREA_UNIT';
const int ARD_PROPERTY_AREA_UNIT_KEY_SQ_FT = 1;
const int ARD_PROPERTY_AREA_UNIT_KEY_SQ_MT = 2;


const String ARD_PROPERTY_TRANSACTION_TYPE = 'PROPERTY_TRANSACTION_TYPE';
const int ARD_PROPERTY_TRANSACTION_TYPE_KEY_SELL = 1;
const int ARD_PROPERTY_TRANSACTION_TYPE_KEY_RENT = 2;
const int ARD_PROPERTY_TRANSACTION_TYPE_KEY_PG = 3;


const String ARD_PROPERTY_AREA_TYPE = 'PROPERTY_AREA_TYPE';
const int ARD_PROPERTY_AREA_TYPE_KEY_CARPET = 1;
const int ARD_PROPERTY_AREA_TYPE_KEY_BUILT_UP = 2;
const int ARD_PROPERTY_AREA_TYPE_KEY_SUPER_BUILT_UP = 3;

const String ARD_PROPERTY_AVAILABLE_TYPE = "PROPERTY_AVAILABLE_TYPE";
const int ARD_PROPERTY_AVAILABLE_TYPE_KEY_DATE = 4;
const String ARD_PROPERTY_FURNISH_TYPE = "PROPERTY_FURNISH_TYPE";
const String ARD_PROPERTY_AGE_TYPE = "PROPERTY_AGE_TYPE";
const String ARD_FLOOR_NO_TYPE = "FLOOR_NO_TYPE";
const int ARD_FLOOR_NO_TYPE_KEY_NO = 1;

const String ARD_PREFERRED_TENANT_TYPE = "PREFERRED_TENANT_TYPE";


const String ARD_PROPERTY_PROFILE_TYPE = "PROPERTY_PROFILE_TYPE";
const int ARD_PROPERTY_PROFILE_TYPE_KEY_ADMIN = 4;
const int ARD_PROPERTY_PROFILE_TYPE_KEY_SUPPORT = 5;

const String ARD_PROPERTY_FACE_TYPE = "PROPERTY_FACE_TYPE";


const String ARD_PROPERTY_LOCALITY_NAME = "PROPERTY_LOCALITY_NAME";


const String ARD_ = "TYPE_NAME";
// APP REF DATA TYPE KEY


// Property Details constant

// DATE_FORMAT

const String DF_DD_MMM_YYYY_SPACE = "d MMM, yyyy";

