// APP_REF_DATA Common Constant

// APP_REF_DATA Property Constant
const String ARD_PROPERTY_TYPE = 'PROPERTY_TYPE';
const String ARD_PROPERTY_TYPE_GROUP = 'PROPERTY_TYPE_GROUP';
const String ARD_PROPERTY_CONFIGURATION_TYPE = 'PROPERTY_CONFIGURATION_TYPE';
const String ARD_PROPERTY_AREA_UNIT = 'PROPERTY_AREA_UNIT';
const String ARD_PROPERTY_AREA_TYPE ='PROPERTY_AREA_TYPE';



